### ISSUE TITLE
Complementación de flechas en el diagrama

### ISSUE THREAD

**Issue by danipaez03** [hemmanuelmiceli/ARGBroker-Demo#2]
![imagen_2024-06-02_212309121](https://github.com/hemmanuelmiceli/ARGBroker-Demo/assets/170897918/71c62296-3976-46a5-b2f4-df5f42f3ed31)

-Identificamos los métodos de cada clase
-Creamos la relación entre cada clase

**Comment by JPsanchezbrandan** [comment]
![Captura de pantalla 2024-06-02 211659](https://github.com/hemmanuelmiceli/ARGBroker-Demo/assets/149123971/cdf95d87-3efa-4463-8547-ea6eb4c94acb)

Aclaraciones: Asociación ha de ir con guion

**Comment by JPsanchezbrandan** [comment]
![Captura de pantalla 2024-06-02 211659](https://github.com/hemmanuelmiceli/ARGBroker-Demo/assets/149123971/d42480a2-134d-47bc-adaf-d05404f39475)

Aclaraciones: Asociación ha de ir con guion

**Comment by Avilla1802** [comment]
Mañana continuaremos con la identificación de los datos en cada atributo.
